
include $(GOROOT)/src/Make.inc

TARG=sid

GOFILES=\
	sid.go \
	config.go \
	control.go \
	doc.go \
	http.go \
	html.go \
	cover.go \
	net.go \
	upload.go \
	utils.go \

include $(GOROOT)/src/Make.pkg
